### ISSUE TITLE
访问https://[你的域名]/link并用你的明文密码替换ca110us

### ISSUE THREAD

**Issue by 9166619** [ca110us/epeius#1]
访问https://[你的域名]/link 得到一个连接导入到v2ray中 连接失败
明文密码替换ca110us其中明文密码是什么?

**Comment by axinhouzilaoyue** [comment]
你在生成密文的网站里，用到的明文啊

![12811714880767_ pic](https://github.com/ca110us/epeius/assets/54179583/89e8189b-2806-41c1-8631-ff98db5deff9)

**Comment by 9166619** [comment]
明白了,感谢`~

**Comment by a1564471347** [comment]
> 你在生成密文的网站里，用到的明文啊
> 
> 
> 
> ![12811714880767_ pic](https://github.com/ca110us/epeius/assets/54179583/89e8189b-2806-41c1-8631-ff98db5deff9)
> 
> 

最后链接打不开什么原因
