### ISSUE TITLE
have an issues about websocket: close 1005 (no status)

### ISSUE THREAD

**Issue by techiewmvp** [ca110us/epeius#6]
不好意思，打扰了，我将你的js代码部署到了cloudflare workers，然后添加了SHA224PASS变量，绑定了自定义域，然后把生成的节点导入到V2rayN中，测试TCPing 结果是通的，但是测试真延迟的时候结果就是-1，V2rayN日志显示app/proxyman/outbound: failed to process outbound traffic > proxy/trojan: connection ends > websocket: close 1005 (no status)
app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
ERROR [2566520797 519ms] inbound/http[http]: process connection from 127.0.0.1:64463: read http request: read tcp 127.0.0.1:10809->127.0.0.1:64463: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by BruceYo8** [comment]
> 不好意思，打扰了，我将你的js代码部署到了cloudflare的workers，然后添加了SHA224PASS变量，绑定了自定义域，然后把生成的节点导入到V2rayN中，但是测试TCPing结果是通的，测试真延迟的时候结果就是-1，V2rayN日志显示app/proxyman/outbound: 处理出站流量失败 > proxy/trojan: 连接结束 > websocket: close 1005 (no status) app/proxyman/inbound: 连接结束 > proxy/http ：连接结束> io：在关闭的管道上读/写 错误[2566520797 519ms]入站/http[http]：来自127.0.0.1:64463的过程连接：读取http请求：读取tcp 127.0.0.1:10809->127.0.0.1： 64463：wsarecv：现有连接被远程主机强制关闭。

伪装域名改成你的自定义域试试？

**Comment by techiewmvp** [comment]
解决了，查了cloudflare日志才知道客户端密码配置错了，可能我理解错了，密码应该是原始的，不是经过sha224转换的，变量设置的目标值是经过sha224转换得到的，程序里应该是把客户端的密码进行sha224运算后再和变量设置的值进行比对。伪装域获取节点的时候程序已经配置好了，不过还是谢谢。
